services:
  - type: web
    name: folil-labs
    runtime: static
    buildCommand: ""
    staticPublishPath: .

  - type: web
    name: folil-labs-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SENDER_EMAIL
        sync: false
      - key: SENDER_PASSWORD
        sync: false
      - key: CONTACT_EMAIL
        value: contacto@folillabs.com
