services:
  - type: web
    name: folil-labs
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SENDER_EMAIL
        scope: run
      - key: SENDER_PASSWORD
        scope: run
      - key: PORT
        value: "8080"
