services:
  - type: web
    name: folil-labs
    runtime: node
    plan: free
    startCommand: node server.js
    envVars:
      - key: SENDER_EMAIL
        scope: run
      - key: SENDER_PASSWORD
        scope: run
